# Generated by Django 5.0.6 on 2024-09-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
