# Generated by Django 5.0.6 on 2024-09-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_image_alter_survey_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
