# Generated by Django 4.2.15 on 2024-09-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_surveyquestion_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSLU5_eUUGBfxfxRd4IquPiEwLbt4E_6RYMw&s', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
